import {
  GET_USERS_ROUTE,
  GET_USER_BY_ID_ROUTE,
  CREATE_USER_ROUTE,
  UPDATE_USER_ROUTE,
  DELETE_USER_ROUTE,
  GET_USER_HOBBIES_ROUTE,
  ADD_USER_HOBBY_ROUTE,
  REMOVE_USER_HOBBY_ROUTE,
} from "./user";

export const APP_ROUTES = [
  GET_USERS_ROUTE,
  GET_USER_BY_ID_ROUTE,
  CREATE_USER_ROUTE,
  UPDATE_USER_ROUTE,
  DELETE_USER_ROUTE,
  GET_USER_HOBBIES_ROUTE,
  ADD_USER_HOBBY_ROUTE,
  REMOVE_USER_HOBBY_ROUTE,
];
